glib fixes
endlessm/libwobbly pull request #11
Opened 2020-06-07 19:53 UTC by hermes83

In order to use the library within gnome shell extensions, the parameters must be pointers

2020-06-07 19:53 UTC, eos-shell-build commented
I don't recognize the submitter as a member of @endlessm. Can somebody in @endlessm verify the patch? See https://phabricator.endlessm.com/w/software/build/ci-integration/#pull-requests for more details.

2020-06-24 15:25 UTC, wjt commented
ok to test

2020-08-10 22:24 UTC, stuaxo commented
I've been using the patches from @hermes83 for the last month or so and everything seems OK.

2020-09-07 07:32 UTC, danigm requested changes
I see here some mix of tabs and spaces for the indentation. Please, fix that and use only spaces, it's better  because it'll be shown the same result no matter what tab space configuration do you have on your code editor.

There are also some trailing white-spaces. Please, try to remove them to avoid introduce not needed characters.

And about the commit message, try to be more descriptive about the changes done and the motivations, this is a good read: https://chris.beams.io/posts/git-commit/

2020-09-07 07:32 UTC, danigm commented on tests/wobbly/glib_api_test.cpp
> +
spaces vs tabs again.

2020-09-07 07:32 UTC, danigm commented on tests/wobbly/glib_api_test.cpp
> +    	AnimationVector size = { 100.0, 100.0 };
spaces vs tabs again.

2020-09-07 07:32 UTC, danigm commented on tests/wobbly/glib_api_test.cpp
> +    	AnimationVector resize_dimensions = { 200.0, 200.0 };
spaces vs tabs again.

2020-09-07 07:32 UTC, danigm commented on tests/wobbly/glib_api_test.cpp
> +    	AnimationVector size = { 100.0, 100.0 };
spaces vs tabs again.

2020-09-07 07:32 UTC, danigm commented on tests/wobbly/glib_api_test.cpp
> +        animation_wobbly_anchor_move_by (anchor, &delta_pos);
spaces vs tabs again, and trailing whitespaces.

2020-09-07 07:32 UTC, danigm commented on tests/wobbly/glib_api_test.cpp
> +        animation_wobbly_anchor_move_by (anchor, &delta_pos);
spaces vs tabs again, and trailing whitespaces.

2020-09-14 09:05 UTC, danigm approved these changes
Looks good to me. Let's merge this.

2020-09-14 09:05 UTC, merged